propel:
  
  _attributes:     { package: plugins.sfPropelPollsPlugin.lib.model }

  sf_polls:
    _attributes:   { phpName: sfPoll, package: plugins.sfPropelPollsPlugin.lib.model }
    id:
    title:         { type: varchar, size: 255, required: true }
    description:   longvarchar
    is_published:  { type: boolean, required: true, default: false }
    is_active:     { type: boolean, required: true, default: false }
    created_at:
    updated_at:

  sf_polls_answers:
    _attributes:   { phpName: sfPollAnswer, package: plugins.sfPropelPollsPlugin.lib.model }
    id:
    poll_id:       { type: integer, foreignTable: sf_polls, foreignReference: id, onDelete: cascade }
    name:          { type: varchar, size: 255, required: true }
    votes:         integer
    created_at:
    updated_at:

  sf_polls_users_answers:
    _attributes:   { phpName: sfPollUserAnswer, package: plugins.sfPropelPollsPlugin.lib.model }
    id:
    poll_id:       { type: integer, foreignTable: sf_polls, foreignReference: id, onDelete: cascade }
    answer_id:     { type: integer, foreignTable: sf_polls_answers, foreignReference: id, onDelete: cascade }
    user_id:       { type: integer }
    ip_address:    varchar(15)
    created_at:
