generator:
  class:                  sfPropelAdminGenerator
  param:
    model_class:          sfPoll
    theme:                default
    fields:
      title:              { name: Title, help: "The title of the poll, usually a question" }
      count_votes:        { name: Number of votes made on poll }
      is_published:       { name: Published, help: Is this poll available? }
      is_active:          { name: Active, help: Is this poll open for voting? }
      admin_answers:      { name: Available answers }
      results:            { name: Current results }
        
    list:
      title:              List of polls
      display:            [ created_at, =title, count_votes, is_active, is_published ]
      object_actions:
        _edit:            ~
        _delete:          ~
      actions:
        _create:          ~
    
    edit:
      title:              Editing %%title%% poll
      display:            [ title, description, _admin_answers, _results, is_published, is_active ]
